# name: Azure Static Web Apps CI/CD

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize, reopened, closed]
#     branches:
#       - main

# jobs:
#   build_and_deploy_job:
#     if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
#     runs-on: ubuntu-latest
#     name: Build and Deploy Job
#     permissions:
#       id-token: write
#       contents: read
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           submodules: true
#           lfs: false

#       - name: Install Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: "18" # Next.js works well on Node 18+

#       - name: Install dependencies
#         run: npm ci

#       - name: Build Next.js app
#         run: |
#           npm run build
#           # Uncomment if doing static export
#           # npm run export

#       - name: Build And Deploy
#         uses: Azure/static-web-apps-deploy@v1
#         with:
#           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_SKY_0D0704C03 }}
#           action: "upload"
#           app_location: "/"
#           api_location: "" # set to "api" if you have Azure Functions
#           output_location: "out" # change to "out" for static export

#   close_pull_request_job:
#     if: github.event_name == 'pull_request' && github.event.action == 'closed'
#     runs-on: ubuntu-latest
#     name: Close Pull Request Job
#     steps:
#       - name: Close Pull Request
#         uses: Azure/static-web-apps-deploy@v1
#         with:
#           action: "close"
