name: Build and deploy Next.js app to Azure Web App - clipwave-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: |
            .next
            public
            package.json
            package-lock.json
            node_modules

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A67216519CC3471DA3022CF2618E67E4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BDC75F76D57B4A57877A2711D3DB73CA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3FF2F47744F641D195B606454A5BDE68 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "clipwave-frontend"
          slot-name: "Production"
          package: .
